### ISSUE TITLE
Build Error: Use of undeclared identifier 'GL_LINE_SMOOTH'

### ISSUE THREAD

**Issue by emorling** [cdave1/ftgles#14]
I am using Xcode9 Beta and getting the following when I build any sample:

"Build error: Use of undeclared identifier 'GL_LINE_SMOOTH'"

Any Ideas?

**Comment by cdave1** [comment]
I'm running Xcode 8.3.3 on 10.12.5 Beta and can't replicate and unable to upgrade. I'm guessing Xcode9 might default to an alternative version of OpenGL, although I can't find any hard evidence that "GL_LINE_SMOOTH" has been removed by Apple in Xcode 9.

Can you perhaps provide some OpenGL version information?  For example:
```
$ glxinfo | grep "OpenGL"
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GT 750M OpenGL Engine
OpenGL version string: 2.1 NVIDIA-10.17.5 355.10.05.45f01
OpenGL shading language version string: 1.20
OpenGL extensions:
```

**Comment by cdave1** [comment]
Ignore my previous message! 

The samples all use GLKit, and I guess Apple recently changed GLKit so the ES1 headers were no longer included by default....?  Anyway, I've pushed an update to the samples, explicitly including the header files. This will fix the build error.

**Comment by emorling** [comment]
Awesome, thanks
